name = "HiGHSGenerator"
uuid = "29d40f5d-5975-4b84-8837-a92f319abcc4"
authors = ["Mathieu Besançon <mathieu.besancon@gmail.com>"]
version = "0.1.0"

[deps]
Clang = "40e3b903-d033-50b4-a0cc-940c62c95e31"

[compat]
Clang = "0.11"
